Resources:

  BucketBeliscoS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: leosouzabh-bucket-1
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      Tags:
        - Key: exemplo
          Value: por que o Edson pediu
        - Key: owner
          Value: data-engineering 2
        - Key: service
          Value: airflow 21

  Bucket2BeliscoS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: leosouzabh-bucket-2
      PublicAccessBlockConfiguration:
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: False